language: python
python:
    - "2.7"

install: "pip install -r requirements.txt -r requirements_tests.txt"

before_script:
    - sudo apt-get install postgresql-9.1
    - sudo -u postgres createdb goattower-tests

script:
    - nosetests --with-coverage --cover-package=. -v goattower/tests

after_success:
    coveralls
